### ISSUE TITLE
messages.add - Only return one message

### ISSUE THREAD

**Issue by jersonjunior** [AbhiSharma1999/RASA-Chatbot#2]
I realized that if rasa returns two messages the app does not print the two messages for the user.

I made a simple adjustment but the ideal would be to return a message and then the other

```
messages.add(Message(
            text: list[0].text, time: time, isMe: false));
      });

```
To:

```
messages.add(Message(
            text: list[0].text + ". " + list[1].text, time: time, isMe: false));
      });
```

**Comment by AbhiSharma1999** [comment]
For my current use case, I only need to display one message so I did not bother to give support for multiple messages. There is a problem with your approach too. You have added support for 2 messages but what if there are multiple. We will have to iterate here and then add to the list.

**Comment by jersonjunior** [comment]
Do you have plans to improve the project?
